name = "herzakoeall"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.172.42.163:3128"
UUID = "5ccc407f-31b7-4fd7-9e17-425ade48a522"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
